### ISSUE TITLE
which ue version is this plugin wroten for ?

### ISSUE THREAD

**Issue by hikingyoung** [AlexanderSartonCozzi/NewEditorMode#1]
Hi 
Just as the title said, I want to know UE4 version for this plugin.

Actually I don't know how to get the right ue4 version of any plugin, do you get a method ?

**Comment by AlexanderSartonCozzi** [comment]
Hi,

I believe I wrote this for 4.17. Unfortunately there is not really a way to directly see which version it is. But off course I could have made a release branch for 4.17 to make clear which version this was made for. If I have some spare time this week I will set that up and also check if this still works correctly for 4.27 and see if the code can use some updates.

**Comment by AlexanderSartonCozzi** [comment]
I added a tag to the current branch so it's more clear this is created for 4.17.

**Comment by hikingyoung** [comment]
> I added a tag to the current branch so it's more clear this is created for 4.17.

Ahh~I see it. YES!

**Comment by hikingyoung** [comment]
> Hi,
> 
> I believe I wrote this for 4.17. Unfortunately there is not really a way to directly see which version it is. But off course I could have made a release branch for 4.17 to make clear which version this was made for. If I have some spare time this week I will set that up and also check if this still works correctly for 4.27 and see if the code can use some updates.

Wow, that would be so nice 0.0

**Comment by AlexanderSartonCozzi** [comment]
Hi @hikingyoung last week I added a release for 4.17 and also did a small update to support 4.27. I also made a new release for that, so they can both be found easily. Next to that I improved the readme to explain a bit more about how the plugin can be used. I will close this issue now, thanks for commenting!
